version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "5001:5001" 

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./database:/data/db

  